export type LeadFormData = {
  lead_stage_id: string;
  date_in: string;
  company_name: string;
  industry: string;
  vacancy_position: string;
  contact_name: string;
  email: string;
  phone: string;
  region: string;
  source: string;
  pic: string;
  assigned_to_ids: number[];
  service_package_ids: number[];
  estimated_value: string;
  last_contact_date: string;
  next_action_date: string;
  next_action: string;
  meeting_date: string;
  temperature: string;
  notes: string;
  folder_url: string;
  status: string;
  lost_reason: string;
};
